apiVersion: v1
kind: LimitRange
metadata:
  name: pod-resource-limits
  namespace: limitranger-demo
spec:
  limits:
  - type: Container
    default:
      cpu: "500m"
      memory: "256Mi"
    defaultRequest:
      cpu: "250m"
      memory: "128Mi"
