apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-db
spec:
  serviceName: db-service  # Link to the headless service
  replicas: 3  # Number of replicas (PostgreSQL pods)
  selector:
    matchLabels:
      app: my-db
  template:
    metadata:
      labels:
        app: my-db
    spec:
      containers:
        - name: database
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: "mysecretpassword"  # Set the password for PostgreSQL
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/postgresql/data  # Path where the DB will store data
  volumeClaimTemplates:
    - metadata:
        name: db-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi  # Requesting 5Gi storage for each pod
