apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: my-container
          image: nginx:latest
          env:
            - name: SERVICE_URL
              value: "$(SERVICE_NAME)"  # Using the variable
