apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yaml
  - deployment.yaml

vars:
  - name: SERVICE_NAME
    objref:
      kind: Service
      version: v1
      name: my-service
